### ISSUE TITLE
about  eq (1) and eq(4)(5)

### ISSUE THREAD

**Issue by WongKinYiu** [HCIILAB/DeRPN#2]
hello, i think eq (1) and eq(4)(5) are equivalent.

![image](https://user-images.githubusercontent.com/12152972/56266484-eb884400-611e-11e9-8b9b-5f5b43038f08.png)

**Comment by Lele-Xie** [comment]
Hi~~The meanings of these equations are totally different. 

In eq(1), the regression operations are based on anchor boxes and both of the width references and height references exactly come from the same anchor box. Therefore, the width references and height references are coupled/relevant, dependent on the settings of anchor boxes.

However, in eq(4)(5), the regressions on width and height are based on anchor strings. Note that the DeRPN independently matches object width or height with the optimal anchor strings. The width references and height references are independent/irrelevant and DeRPN only predicts width segments (x,w) or height segments (y,h).

As for the  engineering implementation, as shown in your figure, we can use one convolution with 4 channel outputs or two convolutions with 2 channel outputs. It doesn't matter.

**Comment by WongKinYiu** [comment]
hello, thank u for ur answer.

i know they have different meaning since the regressions on width eq(4) and height eq(5) will refer to different estimated probabilities in eq(6). but most of deep learning based regression operations treat each variable stands on its own, eq(1) also do not measure dependence between width and height. the width references and height references are coupled/relevant in eq(3) and independent/irrelevant in eq(6).

**Comment by Lele-Xie** [comment]
We are glad to see that you are interested in this question.

Actually, the dependence  we mentioned between the width and height references is latent in eq.1.  This dependence comes from the anchor boxes. For example, we assume that we have predefined anchor boxes a1(x1, y1, w1, h1) and a2(x2, y2, w2, h2). If selecting a1 as  positive, the regression must be based on w1 and h1 simultaneously. If selecting a2 as  positive, the regression must be based on w2 and h2 simultaneously.  Now we can see that, the regressions on width and height for anchor boxes  are coupled/relevant because the width and height reference are bound in an anchor box. For our DeRPN, the width and height references are totally independent. We can select the best matched anchor strings for object width and height, respectively. The pairings between width and height references are not compulsory in DeRPN.

**Comment by WongKinYiu** [comment]
yes, that's what i mean. width and height references has dependence due to estimated probabilities of anchor boxes are calculated by eq(3). so If selecting an unique anchor as positive, the regression must be based on its weight and height simultaneously.

we can select width and height references independently by eq(8).
then, we can apply a more complicate rule or algorithm on results of eq(1) to make width and height references become independent. for example, shuffle width and height references.

thank u for ur clear explanation, i will close this issue.
